location:
  lat: 48.28646434486518
  lon: 17.27221245956356

radii:
  display_meters: 140      # half-size of the visible square around the property

poi:
  show:
    hospital: true
    supermarket: true
    school: true
    kindergarten: true
    pharmacy: true
    bus_stop: true
    train: true
    park: true

cache:
  enabled: true
  dir: .cache

api:
  host: "0.0.0.0"
  port: 8000
